name: Run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Bun
        run: curl -fsSL https://bun.sh/install | bash

      - name: Add Bun to PATH
        run: echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: bun install

      # Ejecutar tests y guardar la salida en un archivo de log
      - name: Run tests
        run: bun test > jest.log 2>&1

      # Guardar el archivo de log como artefacto
      - name: Save test log
        uses: actions/upload-artifact@v3
        with:
          name: jest-log
          path: jest.log
